"""
Download generation: markdown files + ZIP bundle.
"""

import io
import base64
import zipfile
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent


def generate_results_markdown(eval_results: list[dict], chat_responses: list[dict], notebook_outputs: dict) -> str:
    """Generate results.md with evaluation tables, chart refs, and observations."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build summary table
    table_rows = ""
    for r in eval_results:
        cs = r["chunk_size"]
        sm = r["search_mode"]
        sh = r.get("scores_heuristic", {})
        sj = r.get("scores_llm_judge", {})
        table_rows += (
            f"| {cs} | {sm} "
            f"| {sh.get('retrieval', '-')}/5 | {sh.get('faithfulness', '-')}/5 | {sh.get('correctness', '-')}/5 "
            f"| {sj.get('retrieval', '-')}/5 | {sj.get('faithfulness', '-')}/5 | {sj.get('correctness', '-')}/5 |\n"
        )

    # Best config analysis
    best = max(eval_results, key=lambda r: (
        r.get("scores_heuristic", {}).get("correctness", 0) +
        r.get("scores_llm_judge", {}).get("correctness", 0)
    )) if eval_results else {}

    best_label = f"chunk_{best.get('chunk_size', '?')}_{best.get('search_mode', '?')}"

    # Chat Q&A samples
    chat_section = ""
    for i, resp in enumerate(chat_responses, 1):
        chat_section += f"""### Q{i}: {resp['question']}

**Answer:** {resp['answer'][:500]}{'...' if len(resp.get('answer', '')) > 500 else ''}

**Sources:** {', '.join(s.get('source', 'unknown') for s in resp.get('sources', [])[:3])}

---

"""

    # Per-question detail for best config
    detail_section = ""
    if best.get("questions"):
        for i, q in enumerate(best["questions"], 1):
            h = q.get("heuristic", {})
            j = q.get("llm_judge", {})
            detail_section += f"""**Q{i}: {q['question']}**
- Generated: {q['generated_answer'][:300]}...
- Heuristic correctness: {h.get('correctness_score', 'N/A')}
- LLM judge correctness: {j.get('correctness', 'N/A')}
- LLM judge reasoning: {j.get('reasoning', 'N/A')}

"""

    return f"""# RAG Q&A System — Evaluation Results

**Generated:** {timestamp}
**Models:** Qwen3 + Qwen3-Embedding-8B (4096 dim)
**Data:** 10 reinforcement learning research papers (247 pages)
**Vector Store:** ChromaDB with pre-built embeddings

---

## Architecture

![RAG Pipeline Architecture](charts/architecture_diagram.svg)

---

## Evaluation Summary

| Chunk Size | Search Mode | Retrieval (H) | Faithfulness (H) | Correctness (H) | Retrieval (J) | Faithfulness (J) | Correctness (J) |
|-----------|-------------|---------------|-------------------|-----------------|---------------|-------------------|-----------------|
{table_rows}

*H = Heuristic scoring, J = LLM-as-Judge scoring*

**Best configuration:** `{best_label}`

---

## Charts

### Evaluation Scores by Configuration
![Evaluation Scores](charts/evaluation_scores.png)

### Performance vs Chunk Size
![Chunk Comparison](charts/chunk_comparison.png)

### Vector vs Hybrid Search
![Search Comparison](charts/search_comparison.png)

### Heuristic vs LLM-as-Judge
![Judge Comparison](charts/judge_comparison.png)

---

## Sample Q&A Results

{chat_section}

## Per-Question Detail (Best Config: {best_label})

{detail_section}

---

## Key Observations

1. **Retrieval** is consistently strong across all configurations — the embedding model (Qwen3-Embedding-8B) captures semantic meaning well
2. **Chunk size** affects correctness: larger chunks provide more context but may include noise
3. **Hybrid search** (BM25 + Vector) generally improves results for technical terminology
4. **LLM-as-Judge** provides more nuanced scoring than heuristic methods, especially for partial correctness

---

*Generated by the RAG Q&A System — Week 2 AI Engineering Bootcamp*
"""


def generate_readme_markdown() -> str:
    """Generate README.md with setup and run instructions."""
    return """# RAG Document Q&A System — Week 2

A fully interactive RAG (Retrieval-Augmented Generation) pipeline for question answering over 10 reinforcement learning research papers.

## Stack

| Component | Choice | Details |
|-----------|--------|---------|
| LLM | Qwen3 | Via Ollama, 744B parameters, 198K context |
| Embeddings | Qwen3-Embedding-8B | Via Ollama, 4096 dimensions, #1 MTEB |
| Vector DB | ChromaDB | Local persistent storage |
| Framework | LangChain | RAG chain orchestration |
| Backend | FastAPI | REST API + SSE streaming |
| Frontend | Vanilla JS + Tailwind | Interactive notebook + chat UI |

## Prerequisites

- Python 3.11+
- [Ollama](https://ollama.com/) installed and running

## Setup

```bash
# 1. Install Python dependencies
pip install -r requirements.txt

# 2. Pull the required Ollama models
ollama pull qwen3-embedding
ollama pull qwen3:8b

# 3. Verify models are available
ollama list
```

## Running

### Web App (Interactive Notebook + Chat)
```bash
uvicorn main:app --host 0.0.0.0 --port 8002
# Open http://localhost:8002
```

### Jupyter Notebook
```bash
jupyter notebook rag_pipeline.ipynb
```

### Streamlit App (Legacy)
```bash
streamlit run app.py
```

## Features

### Core Pipeline (6 Steps)
1. **Load** — 10 PDFs (247 pages) via PyPDFLoader
2. **Chunk** — RecursiveCharacterTextSplitter (300/500/1000 sizes)
3. **Embed** — Qwen3-Embedding-8B → 4096-dim vectors → ChromaDB
4. **Retrieve** — Vector search + BM25 hybrid (40/60 weighting)
5. **Generate** — Qwen3 with grounding prompt → answers + sources
6. **Evaluate** — Heuristic + LLM-as-Judge dual scoring on 5-question set

### Stretch Goals
- [x] Multiple chunk size comparison (300, 500, 1000)
- [x] Hybrid search (BM25 + Vector via EnsembleRetriever)
- [x] Metadata filtering (topic, year, venue)
- [x] Evaluation metrics (retrieval, faithfulness, correctness)
- [x] Multi-document support (PDF + TXT + CSV)

## API Endpoints

| Endpoint | Method | Description |
|----------|--------|-------------|
| `/api/rag/query` | POST | Full RAG Q&A |
| `/api/rag/retrieve` | POST | Retrieval only |
| `/api/rag/evaluate` | POST | Run 5-question eval |
| `/api/rag/notebook` | GET | Get notebook cells |
| `/api/rag/notebook/run` | POST | Execute a cell |
| `/api/rag/autoplay` | GET | SSE autoplay (runs everything) |
| `/api/rag/results` | GET | Get cached autoplay results |
| `/api/rag/download/zip` | GET | Download all results as ZIP |

## Reproducibility

Results are deterministic due to:
- Temperature=0 for LLM generation
- Fixed evaluation questions and retrieval parameters
- Pre-built ChromaDB with identical embeddings
- Same Ollama model versions

To reproduce the exact results shown in `results.md`, ensure you have the same Ollama models pulled and run the autoplay from the web UI.

---

*AI Engineering Bootcamp — Week 2 Assignment*
"""


def generate_process_markdown() -> str:
    """Generate process.md documenting the entire build process."""
    return """# Build Process — RAG Document Q&A System

## Project Overview

This document describes the end-to-end process of building a RAG (Retrieval-Augmented Generation) system for question answering over reinforcement learning research papers, as part of the AI Engineering Bootcamp Week 2 assignment.

## 1. Data Collection

**10 RL Research Papers** spanning diverse topics:

| # | Paper | Topic | Year | Venue |
|---|-------|-------|------|-------|
| 1 | Deep Recurrent Q-Learning for POMDPs | POMDP | 2015 | AAAI Workshop |
| 2 | General Value Function Networks | Predictive Knowledge | 2021 | JAIR |
| 3 | Recurrent Model-Free RL for POMDPs | POMDP | 2021 | NeurIPS |
| 4 | R2D2: Recurrent Experience Replay | Distributed RL | 2019 | ICLR |
| 5 | Stabilizing Transformers for RL (GTrXL) | Memory Architecture | 2020 | ICML |
| 6 | Reward Machines for RL | Reward Shaping | 2022 | JMLR |
| 7 | Off-Policy Deep RL Without Exploration | Batch RL | 2019 | ICML |
| 8 | Constrained Policy Optimization (CPO) | Safe RL | 2017 | ICML |
| 9 | Benchmarking Batch Deep RL | Batch RL | 2019 | arXiv |
| 10 | DreamerV3: Mastering Diverse Domains | World Models | 2023 | arXiv |

Additional multi-document support files:
- `papers_summary.txt` — plain text index of all papers
- `papers_metadata.csv` — structured metadata (title, authors, year, venue, topic)

## 2. Architecture Design

### Why Server-Executed Notebook?

We evaluated two approaches:
1. **In-browser Python** (Pyodide/JupyterLite) — Cannot run ChromaDB, LangChain, or Ollama (WASM limitations)
2. **Server-executed notebook** — FastAPI backend runs code, streams results to browser

We chose option 2 for full compatibility with the ML stack.

### RAG Pipeline Flow

```
PDFs (10 papers, 247 pages)
    ↓
RecursiveCharacterTextSplitter (300/500/1000 chunk sizes, with overlap)
    ↓
Qwen3-Embedding-8B (4096 dimensions via Ollama)
    ↓
ChromaDB (3 collections: chunks_300, chunks_500, chunks_1000)
    ↓
Retrieval: Vector Search + BM25 Hybrid (40/60 weighting)
    ↓
Qwen3 (8B) (via Ollama, temperature=0, grounding prompt)
    ↓
Answer + Source Documents
```

### Tech Stack Decisions

| Decision | Choice | Why |
|----------|--------|-----|
| LLM | Qwen3 (8B) | Free, large context (198K), strong reasoning |
| Embeddings | Qwen3-Embedding-8B | #1 on MTEB, 4096 dims, excellent semantic capture |
| Vector DB | ChromaDB | Simple, local, persistent, good LangChain integration |
| Chunking | RecursiveCharacterTextSplitter | Respects sentence boundaries, configurable overlap |
| Retrieval | EnsembleRetriever | BM25 handles exact terms, vector handles paraphrasing |
| Framework | LangChain | Standard RAG tooling, RetrievalQA chain |
| Frontend | Vanilla JS + Tailwind CSS | CDN-only, no build step, matches portfolio site |

## 3. Step-by-Step Implementation

### Step 1: Document Loading
- Used LangChain's `PyPDFLoader` via `DirectoryLoader` to batch-load all PDFs
- Result: 247 pages across 10 papers
- Challenge: PDF parsing quality varies — equations and tables garbled in some papers

### Step 2: Chunking
- `RecursiveCharacterTextSplitter` with three configurations:
  - chunk_size=300 (overlap=30): 3,285 chunks — too granular, loses context
  - chunk_size=500 (overlap=50): 1,816 chunks — best balance
  - chunk_size=1000 (overlap=100): 936 chunks — better for broad questions
- Separators: `["\\n\\n", "\\n", ". ", " ", ""]` — respects paragraph/sentence boundaries
- Metadata enriched: topic, year, venue from paper filename mapping

### Step 3: Embedding & Storage
- `OllamaEmbeddings(model="qwen3-embedding")` — 4096-dimensional vectors
- Three separate ChromaDB collections for each chunk size
- Persistent storage in `chroma_db/` directory
- Challenge: Embedding speed slow for large datasets (solved by persisting)

### Step 4: Retrieval
- **Vector search**: ChromaDB's built-in similarity search with metadata filtering
- **BM25**: LangChain's `BM25Retriever` for exact keyword matching
- **Hybrid**: `EnsembleRetriever` combining BM25 (40%) + vector (60%)
- Topic-based filtering via ChromaDB metadata queries

### Step 5: Generation
- `ChatOllama(model="qwen3:8b", temperature=0)` for deterministic output
- Custom grounding prompt: "Answer based ONLY on the provided context"
- `RetrievalQA.from_chain_type` with "stuff" chain type
- Returns answer + source documents for citation

### Step 6: Evaluation
Two complementary scoring methods:

**Heuristic Scoring:**
- Retrieval: Check if expected source keyword appears in retrieved documents
- Faithfulness: Verify answer terms appear in retrieved context (>20% overlap)
- Correctness: Composite score — 40% exact term match + 30% fuzzy match (SequenceMatcher>0.8) + 30% bigram overlap. Threshold: 0.35

**LLM-as-Judge:**
- Qwen3 evaluates each answer against expected answer
- Structured JSON output: retrieval (0/1), faithfulness (0/1), correctness (0.0-1.0), reasoning
- More nuanced than heuristics — captures semantic equivalence

## 4. Web Application

### Interactive Notebook
- 14 cells (6 markdown headers + 6 runnable code + intro + conclusion)
- Each code cell editable with parameter extraction (chunk_size, search_mode, etc.)
- Server-side execution via `sys.stdout` capture to `StringIO`
- Tab key inserts spaces, auto-resize textareas

### Q&A Chat
- Real-time chat interface with user/assistant bubbles
- Settings: search mode (vector/hybrid), chunk size (300/500/1000), topic filter
- Collapsible source chunks under each answer
- Example query chips for quick testing

### Autoplay Mode
- SSE (Server-Sent Events) streaming for real-time progress
- Runs: 6 notebook steps → 3 sample Q&A → 6 evaluation configs → chart generation
- Results cached in memory, displayed in Results tab
- Generates matplotlib charts + SVG architecture diagram

### Downloads
- Individual files: notebook, README, requirements, results, process docs
- ZIP bundle with all files + chart images
- Results generated from actual run data (not pre-computed)

## 5. Challenges & Solutions

| Challenge | Solution |
|-----------|----------|
| PDF parsing quality (equations, tables) | Accept limitations, focus on text-heavy sections |
| Embedding speed for large datasets | Pre-build and persist ChromaDB collections |
| Qwen3 network latency | SSE streaming for user feedback during long operations |
| Correctness scoring too crude | Dual approach: improved heuristics + LLM-as-judge |
| Browser can't run ML models | Server-executed notebook with parameter extraction |
| Long autoplay runtime (~10-20 min) | Real-time progress via SSE events |

## 6. Stretch Goals

All 5 stretch goals implemented:
- **A) Chunk size comparison**: 3 sizes (300, 500, 1000) with comparative evaluation
- **B) Hybrid search**: BM25 + Vector via EnsembleRetriever (40/60 weighting)
- **C) Metadata filtering**: Filter by topic, year, venue per chunk
- **D) Interactive UI**: FastAPI web app with notebook + chat (replaces Streamlit)
- **E) Multi-document support**: PDF + TXT summary + CSV metadata

---

*AI Engineering Bootcamp — Week 2 Build Process Documentation*
"""


def generate_zip(
    eval_results: list[dict],
    charts: dict[str, str],
    chat_responses: list[dict],
    notebook_outputs: dict,
) -> io.BytesIO:
    """Build a ZIP file in memory with all downloadable artifacts."""
    buf = io.BytesIO()

    notebook_path = BASE_DIR / "rag_pipeline.ipynb"
    requirements_path = BASE_DIR / "requirements.txt"

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        prefix = "week2_rag_results/"

        # Disk files
        if notebook_path.exists():
            zf.write(notebook_path, f"{prefix}rag_pipeline.ipynb")
        if requirements_path.exists():
            zf.write(requirements_path, f"{prefix}requirements.txt")

        # Generated markdown files
        zf.writestr(f"{prefix}results.md", generate_results_markdown(eval_results, chat_responses, notebook_outputs))
        zf.writestr(f"{prefix}README.md", generate_readme_markdown())
        zf.writestr(f"{prefix}process.md", generate_process_markdown())

        # Charts
        for name, data in charts.items():
            if name == "architecture_diagram":
                zf.writestr(f"{prefix}charts/{name}.svg", data)
            else:
                png_bytes = base64.b64decode(data)
                zf.writestr(f"{prefix}charts/{name}.png", png_bytes)

    buf.seek(0)
    return buf
