"""
Notebook cell definitions extracted from rag_pipeline.ipynb.
Each cell has pre-computed default outputs from the executed notebook.
"""

NOTEBOOK_CELLS = [
    {
        "cell_id": "intro",
        "cell_type": "markdown",
        "step": None,
        "content": "# RAG Document Q&A System\n## Reinforcement Learning Research Papers\n\nA RAG-powered Q&A system built on 10 reinforcement learning research papers.\n\n**Stack:**\n- **LLM:** Qwen3 via Ollama\n- **Embeddings:** Qwen3-Embedding-8B via Ollama (4096 dimensions)\n- **Vector DB:** ChromaDB\n- **Framework:** LangChain\n\n**Stretch Goals:** A (Chunk Comparison) | B (Hybrid BM25) | C (Metadata Filtering) | D (Web UI) | E (Multi-document)",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step1_header",
        "cell_type": "markdown",
        "step": 1,
        "content": "---\n## Step 1: Load Documents\n\nLoading 10 reinforcement learning research papers (PDFs) using LangChain's `PyPDFLoader` via `DirectoryLoader`.\n\n**Stretch Goal E (Multi-document):** Also loads a summary text file and CSV metadata file.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step1_load",
        "cell_type": "code",
        "step": 1,
        "content": "from langchain_community.document_loaders import PyPDFLoader, DirectoryLoader\n\n# Load all PDF documents\nloader = DirectoryLoader(\"data\", glob=\"**/*.pdf\", loader_cls=PyPDFLoader)\ndocuments = loader.load()\n\nprint(f\"PDF documents loaded: {len(documents)} pages\")\nprint(f\"\\nSample (first page):\")\nprint(f\"  Source: {documents[0].metadata.get('source', 'unknown')}\")\nprint(f\"  Content: {documents[0].page_content[:300]}...\")",
        "default_output": "PDF documents loaded: 247 pages\n\nSample (first page):\n  Source: data\\01_deep_recurrent_q_learning_pomdps.pdf\n  Content: Deep Recurrent Q-Learning for Partially Observable MDPs\nMatthew Hausknecht and Peter Stone\nDepartment of Computer Science\nThe University of Texas at Austin...",
        "is_runnable": True,
        "runner_func": "run_step1_load",
    },
    {
        "cell_id": "step2_header",
        "cell_type": "markdown",
        "step": 2,
        "content": "---\n## Step 2: Chunk Documents\n\nUsing `RecursiveCharacterTextSplitter` to split documents into chunks.\nExperimenting with 3 different chunk sizes (300, 500, 1000) to compare results.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step2_chunk",
        "cell_type": "code",
        "step": 2,
        "content": "from langchain_text_splitters import RecursiveCharacterTextSplitter\n\n# Try different chunk sizes: 300, 500, or 1000\nchunk_size = 500\nchunk_overlap = 50\n\nsplitter = RecursiveCharacterTextSplitter(\n    chunk_size=chunk_size,\n    chunk_overlap=chunk_overlap,\n    separators=[\"\\n\\n\", \"\\n\", \". \", \" \", \"\"]\n)\n\nchunks = splitter.split_documents(documents)\nlengths = [len(c.page_content) for c in chunks]\n\nprint(f\"Chunk size: {chunk_size} | Overlap: {chunk_overlap}\")\nprint(f\"  Total chunks: {len(chunks)}\")\nprint(f\"  Smallest chunk: {min(lengths)} chars\")\nprint(f\"  Largest chunk:  {max(lengths)} chars\")\nprint(f\"  Average chunk:  {sum(lengths)//len(lengths)} chars\")",
        "default_output": "Chunk size: 500 | Overlap: 50\n  Total chunks: 1816\n  Smallest chunk: 3 chars\n  Largest chunk:  500 chars\n  Average chunk:  412 chars",
        "is_runnable": True,
        "runner_func": "run_step2_chunk",
    },
    {
        "cell_id": "step3_header",
        "cell_type": "markdown",
        "step": 3,
        "content": "---\n## Step 3: Embed + Store in ChromaDB\n\nEmbedding chunks using **Qwen3-Embedding-8B** (4096 dimensions, #1 MTEB multilingual) and storing in **ChromaDB** with persistent storage.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step3_embed",
        "cell_type": "code",
        "step": 3,
        "content": "from langchain_ollama import OllamaEmbeddings\nfrom langchain_chroma import Chroma\n\n# Embedding model info\nembedding_model = OllamaEmbeddings(model=\"qwen3-embedding\")\ntest_vec = embedding_model.embed_query(\"test reinforcement learning\")\n\nprint(f\"Embedding model: qwen3-embedding (Qwen3-Embedding-8B)\")\nprint(f\"Embedding dimensions: {len(test_vec)}\")\nprint(f\"Sample values: {test_vec[:5]}\")\n\n# Load existing ChromaDB collection\nchunk_size = 500  # Change to 300 or 1000\nvectorstore = Chroma(\n    collection_name=f\"chunks_{chunk_size}\",\n    embedding_function=embedding_model,\n    persist_directory=\"./chroma_db\",\n)\n\ncount = vectorstore._collection.count()\nprint(f\"\\nChromaDB collection 'chunks_{chunk_size}': {count} vectors stored\")",
        "default_output": "Embedding model: qwen3-embedding (Qwen3-Embedding-8B)\nEmbedding dimensions: 4096\nSample values: [0.030274063, 0.025110206, 0.0018374281, -0.022360569, 0.07703945]\n\nChromaDB collection 'chunks_500': 1816 vectors stored",
        "is_runnable": True,
        "runner_func": "run_step3_embed",
    },
    {
        "cell_id": "step4_header",
        "cell_type": "markdown",
        "step": 4,
        "content": "---\n## Step 4: Test Retrieval (before LLM!)\n\nRunning 3 test queries using `similarity_search` to verify retrieval quality *before* wiring up the LLM.\nFor each query, we print the top 3 retrieved chunks and annotate relevance.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step4_retrieve",
        "cell_type": "code",
        "step": 4,
        "content": "# Test retrieval with 3 queries\nsearch_mode = \"hybrid\"  # Change to \"vector\" for pure vector search\nnum_results = 3\n\ntest_queries = [\n    \"How does DRQN handle partial observability in Atari games?\",\n    \"What is the burn-in technique used in R2D2 for recurrent experience replay?\",\n    \"How does DreamerV3 achieve generalization across diverse domains without tuning?\",\n]\n\nfor i, q in enumerate(test_queries, 1):\n    print(f\"\\n{'='*60}\")\n    print(f\"Query {i}: {q}\")\n    print(f\"{'='*60}\")\n    results = retrieve(q, search_mode=search_mode, num_results=num_results)\n    for j, r in enumerate(results, 1):\n        print(f\"\\n  Chunk {j}: {r['source']} (topic: {r.get('topic', 'N/A')})\")\n        print(f\"  Content: {r['content'][:200]}...\")",
        "default_output": "============================================================\nQuery 1: How does DRQN handle partial observability in Atari games?\n============================================================\n\n  Chunk 1: 01_deep_recurrent_q_learning_pomdps (topic: POMDP)\n  Content: servability, and that when trained with full observations and evaluated with partial observations, DRQN better handles...\n\n  Chunk 2: 01_deep_recurrent_q_learning_pomdps (topic: POMDP)\n  Content: POMDPs by combining a Long Short Term Memory with a Deep Q-Network...\n\n  Chunk 3: 01_deep_recurrent_q_learning_pomdps (topic: POMDP)\n  Content: cle investigates the effects of adding recurrency to a Deep Q-Network (DQN)...\n\n============================================================\nQuery 2: What is the burn-in technique used in R2D2 for recurrent experience replay?\n============================================================\n\n  Chunk 1: 04_recurrent_experience_replay_distributed_rl (topic: Distributed RL)\n  Content: tasks in a benchmark simultaneously while maintaining human-level performance...\n\n  Chunk 2: 04_recurrent_experience_replay_distributed_rl (topic: Distributed RL)\n  Content: We train the R2D2 agent with a single GPU-based learner...\n\n  Chunk 3: 04_recurrent_experience_replay_distributed_rl (topic: Distributed RL)\n  Content: Published as a conference paper at ICLR 2019...\n\n============================================================\nQuery 3: How does DreamerV3 achieve generalization across diverse domains without tuning?\n============================================================\n\n  Chunk 1: 10_mastering_diverse_domains_world_models (topic: World Models)\n  Content: requires significant human expertise and experimentation. We present DreamerV3...\n\n  Chunk 2: 10_mastering_diverse_domains_world_models (topic: World Models)\n  Content: Results We evaluate the generality of Dreamer across 8 domains...\n\n  Chunk 3: 10_mastering_diverse_domains_world_models (topic: World Models)\n  Content: We summarize the changes that DreamerV3 introduces...",
        "is_runnable": True,
        "runner_func": "run_step4_retrieve",
    },
    {
        "cell_id": "step5_header",
        "cell_type": "markdown",
        "step": 5,
        "content": "---\n## Step 5: Build the RAG Chain\n\nWiring up `RetrievalQA` with a custom prompt template that grounds the LLM's answers in the retrieved context.\nRunning the same 3 test queries through the full RAG chain.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step5_query",
        "cell_type": "code",
        "step": 5,
        "content": "# Full RAG Q&A\nsearch_mode = \"hybrid\"  # or \"vector\"\nchunk_size = 500         # 300, 500, or 1000\n\ntest_queries = [\n    \"How does DRQN handle partial observability in Atari games?\",\n    \"What is the burn-in technique used in R2D2 for recurrent experience replay?\",\n    \"How does DreamerV3 achieve generalization across diverse domains without tuning?\",\n]\n\nfor i, q in enumerate(test_queries, 1):\n    print(f\"\\n{'='*60}\")\n    print(f\"Query {i}: {q}\")\n    print(f\"{'='*60}\")\n    result = query(q, search_mode=search_mode, chunk_size=chunk_size)\n    print(f\"\\nAnswer: {result['answer'][:500]}...\")\n    print(f\"\\nSources: {', '.join(s['source'] for s in result['sources'])}\")",
        "default_output": "============================================================\nQuery 1: How does DRQN handle partial observability in Atari games?\n============================================================\n\nAnswer: Based on the provided context, DRQN handles partial observability by combining a Long Short Term Memory (LSTM) with a Deep Q-Network (DQN). Despite observing only a single frame at each timestep, DRQN integrates information across frames to detect relevant details, such as the velocity of on-screen objects.\n\nSources: 01_deep_recurrent_q_learning_pomdps, 01_deep_recurrent_q_learning_pomdps, 01_deep_recurrent_q_learning_pomdps\n\n============================================================\nQuery 2: What is the burn-in technique used in R2D2 for recurrent experience replay?\n============================================================\n\nAnswer: Based on the provided context, the burn-in strategy is described by its hypothesized benefit. The beneficial effect lies in preventing destructive updates to RNN parameters from highly inaccurate initial outputs after zero state initialization.\n\nSources: 04_recurrent_experience_replay_distributed_rl, 04_recurrent_experience_replay_distributed_rl, 04_recurrent_experience_replay_distributed_rl\n\n============================================================\nQuery 3: How does DreamerV3 achieve generalization across diverse domains without tuning?\n============================================================\n\nAnswer: DreamerV3 achieves generalization through robustness techniques based on normalization, balancing, and transformations. Specific techniques include observation symlog, KL balance and free bits, 1% unimix for all categoricals, percentile return normalization, and symexp twohot loss.\n\nSources: 10_mastering_diverse_domains_world_models, 10_mastering_diverse_domains_world_models, 10_mastering_diverse_domains_world_models",
        "is_runnable": True,
        "runner_func": "run_step5_query",
    },
    {
        "cell_id": "step6_header",
        "cell_type": "markdown",
        "step": 6,
        "content": "---\n## Step 6: Evaluate\n\nRunning a 5-question evaluation set with known correct answers.\nScoring each answer on 3 metrics:\n- **Retrieval:** Did we find the right source documents?\n- **Faithfulness:** Is the answer grounded in context (not hallucinated)?\n- **Correctness:** Does the answer match the expected response?\n\nUsing both **improved heuristics** and **LLM-as-judge** for comparison.",
        "default_output": None,
        "is_runnable": False,
    },
    {
        "cell_id": "step6_eval",
        "cell_type": "code",
        "step": 6,
        "content": "# Run full evaluation\nchunk_size = 500          # 300, 500, or 1000\nsearch_mode = \"hybrid\"    # or \"vector\"\nuse_llm_judge = True\nuse_heuristic = True\n\nresults = evaluate(\n    chunk_size=chunk_size,\n    search_mode=search_mode,\n    use_llm_judge=use_llm_judge,\n    use_heuristic=use_heuristic,\n)\n\nfor q in results[\"questions\"]:\n    print(f\"\\nQ: {q['question'][:60]}...\")\n    print(f\"  Answer: {q['generated_answer'][:120]}...\")\n    if \"heuristic\" in q:\n        h = q[\"heuristic\"]\n        r = \"Y\" if h[\"retrieval\"] else \"N\"\n        f = \"Y\" if h[\"faithfulness\"] else \"N\"\n        c = \"Y\" if h[\"correctness\"] else \"N\"\n        print(f\"  Heuristic  -> R:{r} F:{f} C:{c} (score: {h['correctness_score']})\")\n    if \"llm_judge\" in q:\n        j = q[\"llm_judge\"]\n        print(f\"  LLM Judge  -> R:{int(j['retrieval'])} F:{int(j['faithfulness'])} C:{j['correctness']}\")\n        print(f\"  Reasoning: {j['reasoning'][:100]}...\")\n\nprint(f\"\\n{'='*60}\")\nprint(\"SCORES SUMMARY\")\nprint(f\"{'='*60}\")\nif \"scores_heuristic\" in results:\n    s = results[\"scores_heuristic\"]\n    print(f\"Heuristic  -> Retrieval: {s['retrieval']}/5 | Faithfulness: {s['faithfulness']}/5 | Correctness: {s['correctness']}/5\")\nif \"scores_llm_judge\" in results:\n    s = results[\"scores_llm_judge\"]\n    print(f\"LLM Judge  -> Retrieval: {s['retrieval']}/5 | Faithfulness: {s['faithfulness']}/5 | Correctness: {s['correctness']}/5.0\")",
        "default_output": "Q: What architecture does DRQN use to handle partial observabil...\n  Answer: DRQN uses a combination of a Long Short Term Memory (LSTM) and a Deep Q-Network to handle partial observability...\n  Heuristic  -> R:Y F:Y C:N (score: 0.312)\n  LLM Judge  -> R:1 F:1 C:0.75\n  Reasoning: Covers LSTM+DQN combination but doesn't explicitly mention replacing FC layer...\n\nQ: What is the burn-in strategy in R2D2?...\n  Answer: Based on the provided context, the burn-in strategy is described by its hypothesized benefit...\n  Heuristic  -> R:Y F:Y C:N (score: 0.289)\n  LLM Judge  -> R:1 F:1 C:0.5\n  Reasoning: Describes the benefit but not the mechanism of using replay sequence portion...\n\nQ: What is the key contribution of Constrained Policy Optimizat...\n  Answer: CPO is the first general-purpose policy search algorithm for constrained reinforcement learning...\n  Heuristic  -> R:Y F:Y C:Y (score: 0.521)\n  LLM Judge  -> R:1 F:1 C:1.0\n  Reasoning: Perfect match covering constraint satisfaction guarantees and safe RL...\n\nQ: What is the Gated Transformer-XL (GTrXL) and what problem do...\n  Answer: GTrXL modifies the original Transformer by reordering layer normalization and replacing residual connections...\n  Heuristic  -> R:Y F:Y C:Y (score: 0.478)\n  LLM Judge  -> R:1 F:1 C:1.0\n  Reasoning: Covers gating layers, residual connection replacement, and training stability...\n\nQ: How does DreamerV3 handle the challenge of varying signal ma...\n  Answer: DreamerV3 uses robustness techniques including observation symlog and symexp twohot loss...\n  Heuristic  -> R:Y F:Y C:Y (score: 0.445)\n  LLM Judge  -> R:1 F:1 C:0.75\n  Reasoning: Mentions symlog but doesn't isolate it as the specific answer to varying magnitudes...\n\n============================================================\nSCORES SUMMARY\n============================================================\nHeuristic  -> Retrieval: 5/5 | Faithfulness: 5/5 | Correctness: 3/5\nLLM Judge  -> Retrieval: 5/5 | Faithfulness: 5/5 | Correctness: 4.0/5.0",
        "is_runnable": True,
        "runner_func": "run_step6_eval",
    },
    {
        "cell_id": "conclusion",
        "cell_type": "markdown",
        "step": None,
        "content": "---\n## Results\n\n| Metric | Heuristic | LLM Judge |\n|--------|-----------|----------|\n| Retrieval | 5/5 | 5/5 |\n| Faithfulness | 5/5 | 5/5 |\n| Correctness | 3/5 | 4.0/5.0 |\n\n**Key Observations:**\n- Retrieval is excellent — Qwen3-Embedding-8B + BM25 hybrid finds the right papers every time\n- Faithfulness is perfect — the grounding prompt prevents hallucination\n- Correctness improves with LLM-judge (4.0 vs 3) because it captures semantic similarity that keyword heuristics miss\n- Q1 and Q2 are the hardest: the expected answers require very specific architectural details that get paraphrased differently by the LLM",
        "default_output": None,
        "is_runnable": False,
    },
]
